CREATE TEMP FUNCTION render_query(tablename STRING)  RETURNS STRING LANGUAGE js AS """
  return `
-- generated by `bqv alpha template render example template/dataset1/counts.sql --projectid=${GCP_PROJECT_ID} --debug`
SELECT COUNT(1) FROM ${tablename}
  `;
""";

SELECT
  CONCAT(name, "_count") AS name,
  render_query(tablename) AS query,
FROM UNNEST(ARRAY<STRUCT<name string, tablename string>>[
STRUCT(
  "311_request" AS name,
  """`bigquery-public-data.austin_311.311_request`""" AS tablename
)
])

